update launch page
econia-labs/emojicoin-dot-fun pull request #124
Opened 2024-06-23 16:55 UTC by CRBl69

# Description

Update launch page:

- Update button to go to newly registered market.
- Disable button when input is invalid.

# Testing

See vercel.

2024-06-24 21:38 UTC, alnoki approved these changes

2024-06-24 21:40 UTC, alnoki approved these changes

2024-06-24 21:43 UTC, alnoki requested changes
<img width="475" alt="Screenshot 2024-06-24 at 14 42 34" src="https://github.com/econia-labs/emojicoin-dot-fun/assets/43892045/135ad29e-27d5-4fac-9240-c05e5c35c702">

- [x] `~1 APT` (with a space)
- [x] A single heart should not say byte limit reached
- [x] The Emojicoin name should not append `, HEAVY BLACK HEART` for this example
- [ ] Another issue is for `😀` that the name is reported as `GRINNING,GRINNING FACE`

2024-06-26 09:03 UTC, CRBl69 commented
Funny enough, for legacy reasons, the :heart: emoji is actually named "Heavy black heart".

2024-06-27 02:33 UTC, alnoki approved these changes

2024-06-27 02:34 UTC, merged