[ECO-1886] Various chart updates: color scheme, websocket data, fixes
econia-labs/emojicoin-dot-fun pull request #128
Opened 2024-06-26 03:34 UTC by xbtmatt

# Description

- [ ] Update the color scheme to pink and green
- [ ] Incorporate the live websockets data into the chart so the bars update in real time
- [ ] No re-render on props change (every 2-3 seconds the chart would fully reload- disappearing and then reappearing. This is now fixed.

# Testing

Manual with some new unit tests for a few logical functions

# Checklist

- [ ] Did you update relevant documentation?
- [ ] Did you add tests to cover new code or a fixed issue?
- [ ] Did you update the changelog?
- [ ] Did you check all checkboxes from the linked Linear task?

2024-06-29 20:19 UTC, xbtmatt commented on src/typescript/sdk/src/const.ts
> +  PERIOD_1S = 1000000,
Remove before merge again.

2024-06-30 04:03 UTC, xbtmatt commented on src/typescript/sdk/src/const.ts
> + * are all referred to interchangeably throughout this
```suggestion
 * are all referred to interchangeably throughout this codebase.
```

2024-06-30 06:04 UTC, xbtmatt reviewed
Resolve issues with time violations and switching candlestick time frames.

2024-07-01 03:32 UTC, alnoki requested changes
- [ ] Resolve `take out chart search option` from Linear or move to a separate Linear task

2024-07-01 03:32 UTC, alnoki commented on src/typescript/frontend/src/components/charts/README.md
> +<!---cspell:words OHLCV -->
```suggestion
<!---cspell:word OHLCV -->
```

2024-07-01 03:32 UTC, alnoki commented on src/typescript/frontend/src/components/charts/README.md
- [ ] Link to this from a higher-level README, stating that this document captures a lot of the data flow architecture

2024-07-01 04:38 UTC, xbtmatt commented on src/typescript/frontend/src/components/charts/README.md
> +we receive an event in state _and_ the chart is subscribed to a market..
```suggestion
we receive an event in state _and_ the chart is subscribed to a market.
```

2024-07-01 05:28 UTC, xbtmatt commented on src/typescript/frontend/src/components/charts/README.md
Done! added it to `frontend/README.md`

2024-07-01 16:10 UTC, alnoki approved these changes

2024-07-01 16:11 UTC, merged