[ECO-1667] update routing system
econia-labs/emojicoin-dot-fun pull request #160
Opened 2024-07-12 16:36 UTC by CRBl69

# Description

Updates the market routing system:

- market names are defined by the name of the emojis as follows: the name of the market 🍑🍑 is `peach;peach`.
- a market is accessible via `/market/MARKET_NAME`
- going to `/market/EMOJIS` will redirect to `/market/MARKET_NAME`.

For example, when accessing `https://emojicoin.fun/market/🍑🍑`, you will get redirected to `https://emojicoin.fun/market/peach,peach`.

# Testing

See vercel preview.

# Checklist

- [x] Did you check all checkboxes from the linked Linear task?

2024-07-12 17:46 UTC, alnoki requested changes
- [x] Fix broken Vercel deployment
- [x] Fix CI lints

2024-07-12 18:00 UTC, alnoki requested changes
- [x] When I click on the market that is highlighted on the home page, it tries to redirect to the market ID per the old schema, and gives "Emoji not found" error. This should be abstracted as much as possible so that it is only updated in one place for both the cards and for the top one
- [x] How about using an underscore instead of `%20` , e.g `Japanese%20"application"%20button` becomes `Japanes_"application"_button`? (I was originally going to suggest a dash `-` but then I checked `hex_codes` and saw some have a dash in their name, but I don't see any with an underscore). ~Alternatively use `+` as this is how Google, for example, denotes a space~
- [x] Using a comma as a delimiter could be a problem, because some supported coin symbol emojis use on. For example `Person: medium-light skin tone, blond hair`. I'm also concerned that a comma might interfere with chained query parameter parsing. How about a plus? e.g. `peach+peach`?  ~Or if that isn't supported maybe a dunder? `peach__peach`~ (Also consider `Flag: Heard & McDonald Islands`, which as an ampersand `&` )

`folded_hands+folded_hands`

2024-07-18 21:54 UTC, CRBl69 commented
Noting that `;` is used instead of `+` because Vercel converts the `+` to ` ` and cannot differentiated from a real ` `.

2024-07-19 13:47 UTC, alnoki approved these changes

2024-07-19 17:09 UTC, merged