[ECO-2117] Add local docker
econia-labs/emojicoin-dot-fun pull request #210
Opened 2024-08-23 16:30 UTC by CRBl69

# Description

Add a docker compose file to locally deploy the whole stack.

# Testing

Run `docker compose -f compose.yaml -f compose.local.yaml up -d`.

Don't forget to copy `example.local.env` to `.env` first, or alternatively you can run `source example.local.env`.

# Checklist

- [x] Did you check all checkboxes from the linked Linear task?

2024-08-25 21:18 UTC, alnoki requested changes

2024-08-26 02:57 UTC, xbtmatt commented on src/docker/compose.local.yaml
> +    command: aptos node run-local-testnet --with-indexer-api --with-faucet --force-restart --assume-yes --bind-to 0.0.0.0
Removed in #212

2024-08-26 05:04 UTC, xbtmatt commented on src/docker/frontend/Dockerfile
> +ENV REVALIDATION_TIME=$REVALIDATION_TIME
I don't think it does- you need to declare it as an arg for it to be able to be parsed as a variable. At least, I tried it with just `ENV ...` and it didn't work

2024-08-26 05:59 UTC, alnoki commented on src/docker/example.local.env
> +EMOJICOIN_REWARDS_MODULE_ADDRESS="0x4bab58978ec1b1bef032eeb285ad47a6a9b997d646c19b598c35f46b26ff9ece"
Leaving as same in local for ease of setup

2024-08-26 05:59 UTC, alnoki commented on src/docker/example.local.env
> +EMOJICOIN_INTEGRATOR_ADDRESS=0x4bab58978ec1b1bef032eeb285ad47a6a9b997d646c19b598c35f46b26ff9ece
Leaving as same in local for ease of setup

2024-08-26 05:59 UTC, alnoki commented on src/docker/example.testnet.env
> +# PUBLISHER_PK="0x29479e9e5fe47ba9a8af509dd6da1f907510bcf8917bfb19b7079d8c63c0b720"
Taken out from testnet env

2024-08-26 06:05 UTC, alnoki approved these changes

2024-08-26 06:19 UTC, xbtmatt approved these changes

2024-08-26 06:27 UTC, merged