[ECO-2167] Rename all instances of `_PK` to `_PRIVATE_KEY` in favor of being more explicit about the key type
econia-labs/emojicoin-dot-fun pull request #235
Opened 2024-09-04 21:54 UTC by xbtmatt

# Description

Rename *all* instances of `<SOME_ACCOUNT_NAME>_PK` to end with `_PRIVATE_KEY` instead.

This is to avoid confusion between public keys and secret keys, making it slightly more explicit.

# Testing

CI in this PR.

# Checklist

- [x] Did you update relevant documentation?
- [x] Did you add tests to cover new code or a fixed issue?
- [x] Did you update the changelog?
- [x] Did you check all checkboxes from the linked Linear task?

2024-09-05 09:23 UTC, CRBl69 requested changes
It seems that in `src/typescript/sdk/tests/utils/helpers.ts`, there are a couple of `PK` and `pk` left:

```
sdk/tests/e2e/publish.test.ts
20:      pk: publisher.privateKey,

sdk/tests/utils/helpers.ts
9:export const PK_PATH = path.resolve(path.join(TS_UNIT_TEST_DIR, ".tmp", ".pk"));
27:  const pk = fs.readFileSync(PK_PATH).toString();
29:    privateKey: new Ed25519PrivateKey(Hex.fromHexString(pk).toUint8Array()),

sdk/tests/pre-test.js
26:  const pk = await getTestPublisherPrivateKey();
27:  if (!pk) {
30:  fs.writeFileSync(PK_PATH, pk);
31:  const publishResult = JSON.stringify(await publishForTest(pk), null, 2);

sdk/tests/utils/publish.ts
18:  pk: PrivateKey;
24:  const { pk, network, namedAddresses, packageDirRelativeToRoot: packageDirRelative } = args;
42:  const pkString = new Hex(pk.toUint8Array()).toStringWithoutPrefix();
53:    ...["--private-key", pkString],
109:export async function publishForTest(pk: string): Promise<PublishPackageResult> {
112:    privateKey: new Ed25519PrivateKey(Hex.fromHexString(pk).toUint8Array()),
133:    pk: publisher.privateKey,
```

2024-09-05 10:11 UTC, alnoki approved these changes

2024-09-06 22:15 UTC, xbtmatt commented
> It seems that in `src/typescript/sdk/tests/utils/helpers.ts`, there are a couple of `PK` and `pk` left:
> 
> ```
> sdk/tests/e2e/publish.test.ts
> 20:      pk: publisher.privateKey,
> 
> sdk/tests/utils/helpers.ts
> 9:export const PK_PATH = path.resolve(path.join(TS_UNIT_TEST_DIR, ".tmp", ".pk"));
> 27:  const pk = fs.readFileSync(PK_PATH).toString();
> 29:    privateKey: new Ed25519PrivateKey(Hex.fromHexString(pk).toUint8Array()),
> 
> sdk/tests/pre-test.js
> 26:  const pk = await getTestPublisherPrivateKey();
> 27:  if (!pk) {
> 30:  fs.writeFileSync(PK_PATH, pk);
> 31:  const publishResult = JSON.stringify(await publishForTest(pk), null, 2);
> 
> sdk/tests/utils/publish.ts
> 18:  pk: PrivateKey;
> 24:  const { pk, network, namedAddresses, packageDirRelativeToRoot: packageDirRelative } = args;
> 42:  const pkString = new Hex(pk.toUint8Array()).toStringWithoutPrefix();
> 53:    ...["--private-key", pkString],
> 109:export async function publishForTest(pk: string): Promise<PublishPackageResult> {
> 112:    privateKey: new Ed25519PrivateKey(Hex.fromHexString(pk).toUint8Array()),
> 133:    pk: publisher.privateKey,
> ```

Addressed here: https://github.com/econia-labs/emojicoin-dot-fun/pull/235/commits/d7f8f75a431a5cb1ae79b02b9bb8b86dba4c33f9

Thanks for catching this btw

2024-09-08 22:32 UTC, CRBl69 approved these changes

2024-09-09 08:11 UTC, merged