[ECO-2093] Incorporate new fields, APIs, and various other changes into the frontend app
econia-labs/emojicoin-dot-fun pull request #255
Opened 2024-09-20 00:42 UTC by xbtmatt

# Description

This PR merges and fixes all the outgoing issues with the new fields and APIs for the frontend to consume in terms of data from the contract *and* the new indexer processor.

# Testing

Unit/e2e tests in the TypeScript SDK tests

# Checklist

- [x] Did you update relevant documentation?
- [x] Did you add tests to cover new code or a fixed issue?
- [x] Did you update the changelog?
- [x] Did you check all checkboxes from the linked Linear task?

2024-09-26 22:04 UTC, alnoki approved these changes

2024-09-26 22:04 UTC, alnoki commented on src/typescript/.env.ci
>  # Set through CI env variables
```suggestion
# The indexer WebSocket broker endpoint.
```

2024-09-26 22:04 UTC, alnoki commented on src/typescript/.env.ci
> +# The URL for the emojicoin-dot-fun indexer processor.
The indexer REST endpoint.

2024-09-26 22:04 UTC, alnoki commented on src/typescript/.env.example
>  # protocol prefix.
- [ ] Use same as `.env.ci` suggestion

2024-09-26 22:04 UTC, alnoki commented on src/typescript/.env.example
> +# The URL for the emojicoin-dot-fun indexer processor.
- [ ] Use same as for `.env.ci` suggestion

2024-09-26 22:04 UTC, alnoki commented on src/docker/example.local.env
> +# The URL for the emojicoin-dot-fun indexer processor.
- [ ] Use same as for `.env.ci` suggestion

2024-09-27 00:55 UTC, xbtmatt commented on src/typescript/.env.ci
> +# The URL for the emojicoin-dot-fun indexer processor.
Fixed in e272d671

2024-09-27 00:56 UTC, xbtmatt commented on src/typescript/.env.example
>  # protocol prefix.
Fixed in e272d671

2024-09-27 09:46 UTC, CRBl69 requested changes
This is mostly ok.

I think that a lot of changes could have been done in another PR. You made good QoL updates that could have been done a while ago or some time in the future, and that do not have to be in this PR. Although I'm happy they're done, this makes verifying the PR harder both for me and you. Let's focus on that in the future (all of us, I'm guilty of the same crimes :sweat_smile:).

2024-09-27 17:05 UTC, alnoki commented on src/docker/compose.yaml
> +      processor:
Resolving per eng call: postgrest needs RPC call from migrations

2024-09-27 17:06 UTC, alnoki commented on src/typescript/frontend/src/app/page.tsx
Marking resolved per eng call discussion

2024-09-27 17:09 UTC, alnoki commented on src/typescript/sdk/src/broker-v2/index.ts
Flagging we discussed that @xbtmatt can mark resolve once he has addressed

2024-09-27 17:10 UTC, alnoki commented on src/typescript/sdk/src/indexer-v2/queries/app/market.ts
> +    .limit(limit);
Flagging we discussed that @xbtmatt can mark resolve once he has addressed

2024-09-27 17:11 UTC, alnoki commented on src/typescript/sdk/tests/e2e/chat.test.ts
> +  const user = getFundedAccount("006");
Flagging we discussed that @xbtmatt can mark resolve once he has addressed

2024-09-27 17:12 UTC, alnoki commented on src/typescript/sdk/tests/unit/address-derivation.test.ts
> +      emojis: ["0xf09fa693", "0xf09fa79f"],
Flagging we discussed that @xbtmatt can mark resolve once he has addressed

2024-09-27 17:12 UTC, alnoki commented on src/typescript/sdk/tests/e2e/chat.test.ts
> +  const user = getFundedAccount("006");
Noting we just discussed is good as is on eng call

2024-09-27 17:13 UTC, CRBl69 approved these changes

2024-09-27 17:47 UTC, xbtmatt commented on src/typescript/sdk/tests/unit/address-derivation.test.ts
> +      emojis: ["0xf09fa693", "0xf09fa79f"],
Fixed all (or at the ones I could find) instances of this in: c5503207

2024-09-27 17:47 UTC, xbtmatt commented on src/typescript/sdk/src/broker-v2/index.ts
Fixed: c5503207

Thanks for the catch!

2024-09-27 18:04 UTC, xbtmatt commented on src/typescript/sdk/src/indexer-v2/queries/app/market.ts
> +    .limit(limit);
ADdressed in: e603454b, thanks for pointing this out, apparently they can interact separately, but the way we're using them is much simpler with only `range` being used in most cases, the only exception being when we explicitly use `offset` for the periodic state events query from the private charting library.

2024-09-27 23:30 UTC, merged