[ECO-2056] Add e2e search test
econia-labs/emojicoin-dot-fun pull request #309
Opened 2024-10-22 14:01 UTC by CRBl69

# Description

This PR adds an e2e test for the search feature on the home page.

It also fixes may things with the e2e configuration, that will allow the writing of other e2e tests much faster.

# Testing

Ensure CI passes.

2024-10-26 07:01 UTC, xbtmatt reviewed
Looks good so far, just a couple small changes

2024-10-26 07:01 UTC, xbtmatt commented on src/typescript/sdk/tests/post-test.ts
> +  await DockerTestHarness.stop(false);
I think we should make this a named variable or make the function name clearer here. I can't remember what the boolean value does when calling `stop`

It should probably just be two different functions with the functionality conveyed in the function name, and then remove the boolean arg. Easier to read that way

2024-10-28 15:33 UTC, CRBl69 commented on src/typescript/package.json
> +    "e2e:frontend": "turbo run e2e:frontend --filter @econia-labs/emojicoin-frontend --log-prefix none",
Not really.

I updated this in another PR, so I won't update it here again.

2024-10-28 22:07 UTC, xbtmatt requested changes
This looks good overall- but we should really just remove the dotenv runtime stuff here and have your other PR rebase the changes that way we know it's fixed and we don't accidentally keep it in.

In general we should avoid adding anything into the repo that we don't plan on keeping in, it's just ripe for stale/dead code (I know I've done this a few times myself)

2024-10-28 22:07 UTC, xbtmatt commented on src/typescript/frontend/playwright.config.ts
> +dotenv.config({ path: path.resolve(__dirname, "../ci.env") });
```suggestion
```

2024-10-28 22:07 UTC, xbtmatt commented on src/typescript/package.json
> +    "e2e:frontend": "turbo run e2e:frontend --filter @econia-labs/emojicoin-frontend --log-prefix none",
```suggestion
    "e2e:frontend": "pnpm run load-env:e2e-frontend -- turbo run e2e:frontend --filter @econia-labs/emojicoin-frontend --log-prefix none",
```

2024-10-28 22:07 UTC, xbtmatt commented on src/typescript/package.json
> -    "load-env:e2e-frontend": "dotenv -e .env.local -e .env -e .env.example -e ../docker/example.local.env -e ../docker/.env -e ci.env -v NODE_ENV=test",
Add this back in and update it in the other PR when rebasing

2024-10-30 05:47 UTC, xbtmatt approved these changes
Thanks for all the changes on this :) Looks great

2024-10-30 10:48 UTC, merged