[ECO-2354] Add slippage and gas on trading page
econia-labs/emojicoin-dot-fun pull request #317
Opened 2024-10-30 14:34 UTC by CRBl69

# Description

This PR adds the gear for settings and the gas display on the trading page.

# Testing

See vercel.

2024-10-30 16:25 UTC, alnoki commented on src/typescript/frontend/src/components/pages/emojicoin/components/trade-emojicoin/SwapButton.tsx
- [ ] Use `APT` in the gas amount printout
- [ ] Hard-code the amount for when using Aptos Connect

2024-10-31 02:32 UTC, xbtmatt requested changes
It looks like you have an infinite re-render issue somewhere, when I look at the preview page I get this:

```shell
Maximum update depth exceeded. This can happen when a component 
repeatedly calls setState inside componentWillUpdate or 
componentDidUpdate. React limits the number of nested updates to prevent
infinite loops.
```

2024-10-31 11:33 UTC, CRBl69 commented
@xbtmatt what page are you getting that on exactly ? I can't reproduce it.

2024-10-31 11:43 UTC, CRBl69 commented
Nevermind, I fixed it.

2024-11-08 03:54 UTC, xbtmatt approved these changes
This looks incredible! Thanks for doing this, it's really slick, love the way it looks.

2024-11-08 03:54 UTC, xbtmatt commented on src/typescript/frontend/src/components/selects/trade-options/index.tsx
> +                className={`${maxSlippageMode === "custom" ? "text-black" : "text-dark-gray"} font-pixelar text-2xl cursor-pointer`}
```suggestion
                className={`${maxSlippageMode === "custom" ? "opacity-30" : "opacity-100"} text-black font-pixelar text-2xl cursor-pointer`}
```

2024-11-08 03:54 UTC, xbtmatt commented on src/typescript/frontend/src/components/selects/trade-options/index.tsx
> +              className={`${maxSlippageMode === "custom" ? "text-black border-black" : "text-dark-gray border-dark-gray"} flex flex-row border-[1px] p-[.2rem] rounded border-solid`}
```suggestion
              className={`${maxSlippageMode === "custom" ? "opacity-100" : "opacity-30"} text-black border-black flex flex-row border-[1px] p-[.2rem] rounded border-solid`}
```

2024-11-08 03:54 UTC, xbtmatt commented on src/typescript/frontend/src/components/selects/trade-options/index.tsx
> +                className={`${maxSlippageMode === "auto" ? "text-black" : "text-dark-gray"} font-pixelar text-2xl cursor-pointer`}
```suggestion
                className={`${maxSlippageMode === "auto" ? "opacity-100" : "opacity-30"} text-black font-pixelar text-2xl cursor-pointer`}
```

2024-11-08 03:54 UTC, xbtmatt commented on src/typescript/frontend/src/components/selects/trade-options/index.tsx
> +  StyledDropdownMenuClose,
```suggestion
```

2024-11-08 03:54 UTC, xbtmatt commented on src/typescript/frontend/src/components/selects/trade-options/index.tsx
> +      </StyledDropdownMenuClose>
```suggestion
```

Much cleaner without the close here imo, plus it already disappears if you click off of it, like the wallet adapter dropdown. Looks incredible this way too :)

2024-11-08 03:54 UTC, xbtmatt commented on src/typescript/frontend/src/lib/hooks/queries/use-simulate-swap.ts
> +      const swapName = `${MODULE_ADDRESS}::${EMOJICOIN_DOT_FUN_MODULE_NAME}::Swap`;
```suggestion
```

2024-11-08 03:54 UTC, xbtmatt commented on src/typescript/frontend/src/lib/hooks/queries/use-simulate-swap.ts
> +import { EMOJICOIN_DOT_FUN_MODULE_NAME, MODULE_ADDRESS } from "@sdk/const";
```suggestion
import { STRUCT_STRINGS } from "@sdk/utils";
```

2024-11-08 03:54 UTC, xbtmatt commented on src/typescript/frontend/src/lib/hooks/queries/use-simulate-swap.ts
> +      const swapEvent = res.events.find((e) => e.type === swapName)!;
```suggestion
      const swapEvent = res.events.find((e) => e.type === STRUCT_STRINGS.SwapEvent)!;
```

2024-11-08 04:08 UTC, xbtmatt commented on src/typescript/frontend/src/components/pages/emojicoin/components/trade-emojicoin/SwapButton.tsx
Resolving this as both were addressed!

2024-11-08 04:17 UTC, xbtmatt commented on src/typescript/frontend/src/components/selects/trade-options/index.tsx
> +                className={`${maxSlippageMode === "custom" ? "opacity-30" : "opacity-100"} text-black font-pixelar text-2xl cursor-pointer`}
```suggestion
                className={`${maxSlippageMode === "custom" ? "opacity-100" : "opacity-30"} text-black font-pixelar text-2xl cursor-pointer`}
```

2024-11-08 06:06 UTC, merged