[ECO-2618] Add emojicoin arena events, update lock in logic
econia-labs/emojicoin-dot-fun pull request #478
Opened 2024-12-20 23:44 UTC by alnoki

# Description

## Logic updates

1. Require that if a user has locked in since their most recent to an empty
   escrow, they must select lock in on subsequent top-off operations.
1. Assorted abstractions, helpers.

## Events

1. User events
   1. `Enter`
   1. `Exit`
   1. `Swap`
1. State events
   1. `EscrowState`
   1. `MeleeState`
   1. `RegistryState`
1. `NewMelee`
1. `VaultBalanceUpdate`

# Testing

```sh
git ls-files | entr -c sh -c " \
    aptos move compile --dev --move-2  &&
    aptos move fmt \
"
```

# Checklist

- [x] Did you check all checkboxes from the linked Linear task?

2025-01-02 13:47 UTC, CRBl69 requested changes
Look mostly good :+1:

Just a couple of DX changes.

2025-01-02 13:47 UTC, CRBl69 commented on src/move/emojicoin_arena/sources/emojicoin_arena.move
> +        octas_matched: u64,
Could we keep the naming consistent with the event above ?

For example, I think `octas_matched` is basically `match_amount` and `octas_entered` is basically `input_amount`, yet they're named differently.

2025-01-02 13:47 UTC, CRBl69 commented on src/move/emojicoin_arena/sources/emojicoin_arena.move
> +        octas_matched: u64,
Same as above, can we keep this consistent ?

2025-01-02 13:47 UTC, CRBl69 commented on src/move/emojicoin_arena/sources/emojicoin_arena.move
> +        octas_matched: u64,
Same consistency comment as above.

2025-01-02 13:47 UTC, CRBl69 commented on src/move/emojicoin_arena/sources/emojicoin_arena.move
> +        market_metadatas: vector<MarketMetadata>,
Is it possible to have `emojicoin_0_...` and `emojicoin_1_...` just like in the other places here ?

2025-01-02 13:47 UTC, CRBl69 commented on src/move/emojicoin_arena/sources/emojicoin_arena.move
> +        max_match_percentage: u64,
Shouldn't this be just `match_percentage` ? How would the match percentage be dynamic inside a melee (besides the last match(es) where there might not be enough APT left) ?

2025-01-02 13:47 UTC, CRBl69 commented on src/move/emojicoin_arena/sources/emojicoin_arena.move
> +    }
Is there a reason we don't use Q64 just like for the other places ?

It would enable easy comparison.

2025-01-02 13:47 UTC, CRBl69 commented on src/move/emojicoin_arena/sources/emojicoin_arena.move
> +    }
Could we have `octas_initial_value` (octas value at time of enter) and `octas_current_value` (currently `octas_value`) ?

This would mean that $\\rm{octas\\_gain} = \\rm{octas\\_current\\_value} - \\rm{octas\\_initial\\_value}$, so no need to include the three other fields (`octas_{gain,loss,growth_q64}`).

I think it will also be useful to have the initial amount in the frontend.

2025-01-03 00:08 UTC, alnoki commented on src/move/emojicoin_arena/sources/emojicoin_arena.move
> +        max_match_percentage: u64,
> How would the match percentage be dynamic inside a melee

The max match percentage is the amount matched if a user joins at the beginning of the melee. For example as much as 50% match. However if they join halfway through the melee, the most they'll get is 25%

This is the linear decay model we decided on

2025-01-03 00:10 UTC, alnoki commented on src/move/emojicoin_arena/sources/emojicoin_arena.move
> +    }
It's possible, I just went with the ratio because this is the exact amount defined by the ratio of coins as reserves

Also makes it easier to do conversions, e.g. using a `mul_div` operation than having to cast in to Q64 etc.

If we need total order for exchange rate, thoughts on just having it get computed at indexer time by the processor?

2025-01-03 00:13 UTC, alnoki commented on src/move/emojicoin_arena/sources/emojicoin_arena.move
> +    }
Since users can enter multiple times, the `initial_value` descriptor isn't totally accurate, however I do understand the rationale for using a difference here and for including the reference value `octas_entered` for the frontend

Mainly the `octas_gain` field is because that is used for determining the top gains

2025-01-03 00:14 UTC, alnoki commented on src/move/emojicoin_arena/sources/emojicoin_arena.move
> +        market_metadatas: vector<MarketMetadata>,
So are you suggesting something like:

```rust
emojicoin_0_market_metadata: MarketMetadata
emojicoin_1_market_metadata: MarketMetadata
```

?

2025-01-03 00:24 UTC, alnoki commented on src/move/emojicoin_arena/sources/emojicoin_arena.move
> +        octas_matched: u64,
`octas_matched` renamed to `match_amount` in 8b530564

2025-01-03 00:26 UTC, alnoki commented on src/move/emojicoin_arena/sources/emojicoin_arena.move
> +        octas_matched: u64,
`octas_entered` renamed to `input_amount` in 5dc785f5

2025-01-03 00:27 UTC, alnoki commented on src/move/emojicoin_arena/sources/emojicoin_arena.move
> +        octas_matched: u64,
Addressed per https://github.com/econia-labs/emojicoin-dot-fun/pull/478#discussion_r1901389348 https://github.com/econia-labs/emojicoin-dot-fun/pull/478#discussion_r1901390311

2025-01-03 00:27 UTC, alnoki commented on src/move/emojicoin_arena/sources/emojicoin_arena.move
> +        octas_matched: u64,
Addressed per https://github.com/econia-labs/emojicoin-dot-fun/pull/478#discussion_r1901389348 https://github.com/econia-labs/emojicoin-dot-fun/pull/478#discussion_r1901390311

2025-01-03 00:31 UTC, alnoki commented on src/move/emojicoin_arena/sources/emojicoin_arena.move
>          all_entrants: SmartTable<address, Nil>,
Per @davidiw

> Also a quick hint, smart table has a potential denial of service is one of the buckets gets excessively used... as you know address generation can be particularly easy to manipulate within certain constraints, so would have to check the bucketing logic to determine how easily this could result in a broken or excessively expensive smart table.
Update: since the address is hard to fully generate and it goes through another hash (siphash), the impact is likely negligible.

2025-01-03 00:31 UTC, alnoki commented on src/move/emojicoin_arena/sources/emojicoin_arena.move
>      struct UserMelees has key {
Per @davidiw

>  it isn't clear to me why you track UserMelees on-chain when events should suffice -- as the data doesn't seem read on-chain.

2025-01-04 21:49 UTC, alnoki commented on src/move/emojicoin_arena/sources/emojicoin_arena.move
>      struct UserMelees has key {
Resolved per new lightweight indexing model

2025-01-04 21:49 UTC, alnoki commented on src/move/emojicoin_arena/sources/emojicoin_arena.move
>          all_entrants: SmartTable<address, Nil>,
Resolved per removal of `SmartTable` structs

2025-01-04 21:50 UTC, alnoki commented on src/move/emojicoin_arena/sources/emojicoin_arena.move
> +    }
@CRBl69 per the recent lightweight data model we discussed, this can all be done offchain. Note that I even added an example in the new README about indexing PnL and how all the information is there

2025-01-07 18:07 UTC, alnoki commented on src/move/emojicoin_arena/sources/emojicoin_arena.move
> +    }
Marking resolved per eng call and new lightweight indexing

2025-01-07 18:17 UTC, CRBl69 approved these changes

2025-01-07 18:31 UTC, merged