[ECO-2573] Denominate market cap in usd
econia-labs/emojicoin-dot-fun pull request #492
Opened 2024-12-31 13:13 UTC by CRBl69

# Description

This PR denominates market cap on the home page and the market page in USD.

It uses CoinMarketCap to get the APT price in USD and falls back to showing prices in APT if the price cannot be queried.

# Testing

Go to market page and home page on vercel.

# Checklist

- [x] Did you check all checkboxes from the linked Linear task?

2024-12-31 19:47 UTC, alnoki commented on src/typescript/frontend/src/app/dev/verify_api_keys/page.tsx
> +  // Check that CoinMarketCap API key works
- [ ] Try CoinGecko, ideally without an API key if possible
- [ ] Mark as resolved this comment if able to use it

2025-01-02 18:29 UTC, alnoki commented on src/typescript/frontend/src/app/dev/verify_api_keys/page.tsx
> +    throw new Error(`Couldn't fetch APT price.\n\tInvalid CoinGecko API key.`);
- [ ] If unable to fetch price at runtime (either because key is invalid or not present), fall back to APT market cap behavior
- [ ] Fail at build time if key is provided but invalid
- [ ] Allow build if API key not provided
- [ ] Resolve this comment once all above addressed

2025-01-03 14:58 UTC, CRBl69 commented on src/typescript/frontend/src/app/dev/verify_api_keys/page.tsx
> +    throw new Error(`Couldn't fetch APT price.\n\tInvalid CoinGecko API key.`);
Updated behaviour:

- API key is only checked at build time on Vercel.
- At runtime, if the key does not work, falls back to showing prices in APT.

2025-01-03 16:57 UTC, alnoki commented on src/typescript/frontend/src/app/dev/verify_api_keys/page.tsx
> +    throw new Error(`Couldn't fetch APT price.\n\tInvalid CoinGecko API key.`);
@CRBl69 I believe these updates address the above items, but yielding to you to check them off. I'll leave an approving review so once you check them all off and mark this as resolved you can merge

2025-01-03 16:57 UTC, alnoki approved these changes

2025-01-03 16:58 UTC, alnoki approved these changes

2025-01-03 18:40 UTC, alnoki commented on src/typescript/frontend/src/lib/queries/get-apt-price.ts
> +import { COINGECKO_API_KEY } from "lib/server-env";
- [ ] Document this in example.env as I said here: https://github.com/econia-labs/emojicoin-dot-fun/pull/492#discussion_r1901981740

2025-01-05 05:17 UTC, xbtmatt requested changes
1. Move context to the `providers.tsx` file, noted in one of the comments
2. Move market cap logic to `useMarketCap` hook and re-use it to avoid duplicating that logic
3. Make sure everything works without an API key and that all values default to non-USD prices when no API key is provided

Looks good for the most part though :)

2025-01-05 05:17 UTC, xbtmatt commented on src/typescript/frontend/src/app/home/page.tsx
> +    <AptPriceContextProvider aptPrice={aptPrice}>
This should definitely go in `providers.tsx`, otherwise it's conditional based on whether or not the user is visiting the home page, but also because `providers.tsx` wraps the global `layout.tsx` or vice versa (can't remember)

2025-01-05 05:17 UTC, xbtmatt commented on src/typescript/frontend/src/app/market/[market]/page.tsx
> +import { AptPriceContextProvider } from "context/AptPrice";
```suggestion
```

2025-01-05 05:17 UTC, xbtmatt commented on src/typescript/frontend/src/app/market/[market]/page.tsx
> +      <AptPriceContextProvider aptPrice={aptPrice}>
```suggestion
```

2025-01-05 05:17 UTC, xbtmatt commented on src/typescript/frontend/src/app/market/[market]/page.tsx
> +      </AptPriceContextProvider>
```suggestion
```

2025-01-05 05:17 UTC, xbtmatt commented on src/typescript/frontend/src/components/pages/emojicoin/components/main-info/MainInfo.tsx
> +  const usdMarketCap = aptPrice ? toNominal(marketCap) * aptPrice : undefined;
This should be in its own hook, that way you can deduplicate the logic, since it's copy pasted a few times

2025-01-05 05:17 UTC, xbtmatt commented on src/typescript/frontend/src/components/pages/home/components/main-card/MainCard.tsx
> +  const usdMarketCap = aptPrice ? toNominal(marketCap) * aptPrice : undefined;
swap with `useMarketCap` hook (mentioned above)

2025-01-05 05:17 UTC, xbtmatt commented on src/typescript/frontend/src/components/pages/home/components/table-card/TableCard.tsx
> +  const usdMarketCap = aptPrice ? toNominal(marketCap) * aptPrice : undefined;
swap with `useMarketCap` hook (mentioned above)

2025-01-05 05:17 UTC, xbtmatt commented on src/typescript/frontend/src/lib/queries/get-apt-price.ts
> +  { revalidate: 60 * 10 } // Ten minutes
What's the API rate limit? I think this could/should just be 1 minute

2025-01-06 19:31 UTC, xbtmatt reviewed
Two things left after reviewing on eng call:

1. Move market cap logic to a hook
2. Use the new rate limit info to change the polling interval (if the rate limit is generous enough to withstand 1 min per call)

2025-01-06 20:22 UTC, xbtmatt commented on src/typescript/frontend/src/hooks/use-usd-market-cap.ts
> +// If the APT price isn't available, undefined will be returned.
```suggestion
/**
 * Returns the market cap in USD.
 *
 * If the APT price isn't available, it will return `undefined`.
 */
```

2025-01-06 20:23 UTC, xbtmatt commented on src/typescript/frontend/src/lib/queries/get-apt-price.ts
> +  { revalidate: 60 * 10 } // Ten minutes
```suggestion
  { revalidate: 10 } // Ten seconds.
```

2025-01-06 20:25 UTC, xbtmatt commented on src/typescript/frontend/src/app/home/page.tsx
> +    <AptPriceContextProvider aptPrice={aptPrice}>
Determined on call that we'll keep this the same- it's too difficult to change. The reason it's done this way is because we need to pass server data to the layout, and the layout providers.tsx is technically a client component. There's no easy way to get around this other than a global zustand store, which isn't worth the effort + re-rendering. It makes more sense to just wrap the components that need it with the provider.

2025-01-06 20:25 UTC, xbtmatt approved these changes

2025-01-06 23:56 UTC, merged