[ECO-1713] add utility function to check if someone is allowlisted
econia-labs/emojicoin-dot-fun pull request #88
Opened 2024-06-03 01:43 UTC by CRBl69

# Description

This PR adds an `isAllowListed` function that checks if someone is allowlisted.

I was not sure where to incorporate this so I made it as a function that can be
called anywhere, to be incorporated later.

# Testing

Run `deno`, declare the constants used, paste the function, call the function.

See Linear task for a campaign ID.

# Checklist

- [x] Did you update relevant documentation?
- [x] Did you check all checkboxes from the linked Linear task?

2024-06-03 17:27 UTC, alnoki requested changes
- [ ] Add env vars to `src/typescript/.env.example`

2024-06-04 17:53 UTC, xbtmatt approved these changes

2024-06-04 17:55 UTC, alnoki commented on src/typescript/.env.example
> +GALXE_CAMPAIGN_ID=""
Make `NEXT_PUBLIC`

2024-06-04 17:56 UTC, alnoki commented on src/typescript/.env.example
> +ALLOWLISTER3K_URL=""
Do *NOT* make `NEXT_PUBLIC` elsewhere

2024-06-04 17:56 UTC, alnoki commented on src/typescript/frontend/src/lib/env.ts
> +const ALLOWLISTER3K_URL: string | undefined = process.env.NEXT_PUBLIC_ALLOWLISTER3K_URL;
Take out `NEXT_PUBLIC`

2024-06-04 17:58 UTC, alnoki commented on src/typescript/frontend/src/lib/env.ts
> +const IS_ALLOWLIST_ENABLED: boolean = process.env.NEXT_PUBLIC_IS_WHITELIST_ENABLED === "true";
`WHITELIST` -> `ALLOWLIST`

2024-06-04 17:59 UTC, xbtmatt requested changes
Add `import "server-only"` to the top of the `*.ts` queries

2024-06-04 20:33 UTC, alnoki commented on src/typescript/frontend/src/lib/env.ts
Marking complete per https://github.com/econia-labs/emojicoin-dot-fun/pull/88#pullrequestreview-2097074197

2024-06-05 17:07 UTC, alnoki requested changes
- [x] Rebase per recent submodule updates to inbox

2024-06-06 17:26 UTC, xbtmatt commented on src/typescript/.env.example
> +ALLOWLISTER3K_URL=""
You should also change the file name to `server-env.ts` to be more accurate, since it's not just at build time but for anything server-side

2024-06-06 17:30 UTC, xbtmatt approved these changes

2024-06-06 17:32 UTC, alnoki approved these changes

2024-06-06 17:32 UTC, merged